---
abstract: 'Everyone wants to be like me!'
author:
  - 'Logan Bell <loganbell@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-LOGIE
requires:
  App::Ack: 0
  DBIx::Class: 0
  DateTime: 0
  Dist::Zilla: 0
  Moo: 0
  Moose: 0
  Plack: 0
  Test::Most: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/logie17/Task-BeLike-LOGIE
version: 0.001
